#TUTORIAL 1


## Basic Variable Types

In [1]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [2]:
mi_cadena1='Bienvenido Carlos a'
mi_cadena2 ="QuantConnect"
print(mi_cadena1 +' '+mi_cadena2)

Bienvenido Carlos a QuantConnect


In [3]:
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [4]:
mi_entero=100
print(mi_entero)
print(type(mi_entero))

100
<class 'int'>


In [5]:
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [6]:
mi_cadena="100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
print(type(mi_cadena))
mi_entero=int(mi_cadena)
print(mi_entero)
print(type(mi_entero))

<class 'str'>
100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<class 'int'>


In [7]:
my_float = 1.0
print(type(my_float))
my_int = 1
print(type(my_int))

<class 'float'>
<class 'int'>


In [8]:
mi_flotante=1.1
print(type(mi_flotante))
mi_entero=1
print(type(mi_entero))

<class 'float'>
<class 'int'>


In [9]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [10]:
mi_cadena="10000000"
mi_flotante=float(mi_cadena)
print(mi_flotante)
print(type(mi_cadena))

10000000.0
<class 'str'>


In [11]:
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [12]:
mi_booleano = True
print(mi_booleano)
print(type(mi_booleano))

True
<class 'bool'>


##Basic Math Operations

In [13]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [14]:
print("Suma ", 8+1000)
print("Resta ", 5-9)
print("Multiplicación ", 2*7)
print("División ", 10/12)
print("potencia ", 2**4)

Suma  1008
Resta  -4
Multiplicación  14
División  0.8333333333333334
potencia  16


##Data Collections


###List

In [15]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [16]:
mi_lista=["Hola","Mundo",'Hola','Carlos',3,2,1]
print(mi_lista)

['Hola', 'Mundo', 'Hola', 'Carlos', 3, 2, 1]


In [17]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Quant
3


In [18]:
mi_lista=['Hola','Carlos',1,0,3,5,8]
print(len(mi_lista))
print(mi_lista[0])
print(mi_lista[1])
print(mi_lista[len(mi_lista)-3])

7
Hola
Carlos
3


In [19]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [20]:
mi_lista=['Hola','Carlos',1,0,3,5,8]
mi_lista[1]='Mundo'
print(mi_lista)

['Hola', 'Mundo', 1, 0, 3, 5, 8]


In [21]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [22]:
mi_lista=['Hola','Carlos',1,0,3,5,8]
print(mi_lista[1:4])

['Carlos', 1, 0]


In [23]:
print(my_list[1:])

['Connect', 1, 2, 3]


In [24]:
print(mi_lista[1:])

['Carlos', 1, 0, 3, 5, 8]


In [25]:
print(my_list[:3])

['Quant', 'Connect', 1]


In [26]:
print(mi_lista[:2])

['Hola', 'Carlos']


In [27]:
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)
my_list.remove('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [28]:
mi_lista=['Hola','Mundo']
mi_lista.append('Hola')
print(mi_lista)
mi_lista.remove('Hola')
print(mi_lista)

['Hola', 'Mundo', 'Hola']
['Mundo', 'Hola']


###Tuple

In [29]:
my_tuple = ('Welcome','to','QuantConnect')

In [30]:
mi_tupla=('Bienvenido','a','QuantConnect')

In [31]:
my_tuple = ( 'Welcome' , 'to' , 'QuantConnect' )
print( my_tuple [ 1 :]) 

('to', 'QuantConnect')


In [32]:
mi_tupla=('Bienvenido','a','QuantConnect')
print(mi_tupla[1:])

('a', 'QuantConnect')


###Set

In [33]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'IBM', 'F', 'GOOG', 'AAPL', 'FB'}


In [34]:
lista=['Carlos','Juan','Andrea','andrea','Juan','Pepito']
lista_set= set(lista)
print(lista_set)

{'Carlos', 'Pepito', 'andrea', 'Andrea', 'Juan'}


###Dictionary

In [35]:
my_dic = { 'AAPL' : 'Apple' , 'FB' : 'FaceBook' , 'GOOG' : 'Alfabeto' }   

In [36]:
mi_diccionario = { 'C' : 'Carlos' , 'J' : 'Juan' , 'A' : 'Andrea' , 'a' : 'andrea' , 'P' : 'Pepito'}   

In [37]:
print ( my_dic [ 'GOOG' ]) 

Alfabeto


In [38]:
print(mi_diccionario['A'])

Andrea


In [39]:
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [40]:
mi_diccionario['P']='Pedro'
print(mi_diccionario['P'])
print(mi_diccionario)

Pedro
{'C': 'Carlos', 'J': 'Juan', 'A': 'Andrea', 'a': 'andrea', 'P': 'Pedro'}


In [41]:
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [42]:
print(mi_diccionario.keys())

dict_keys(['C', 'J', 'A', 'a', 'P'])


##Common String Operations

In [43]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [44]:
mi_str='Bienvenido a QuantConnect'
print(mi_str[11:])

a QuantConnect


In [45]:
print("Counting the number of e's in this sentence".count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))

6
2
ell the e in this sentence now becomes e


In [46]:
print("Cuenta el numero de e's in esta sentencia".count('e'))
print("La primera vez que e aparece en esta sentencia".find('e'))
print('todas las a en esta sentencia ahora se convierten en e'.replace('a','e'))

8
7
todes les e en este sentencie ehore se convierten en e


In [47]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)

2016-04-01 09:43:00
09


In [48]:
Tiempo='2021-10-15 18:15:00'
lista_dividida=Tiempo.split(' ')
fecha=lista_dividida[0]
tiempo=lista_dividida[1]
print(fecha,tiempo)
hora=tiempo.split(':')[0]
print(hora)

2021-10-15 18:15:00
18


In [49]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [50]:
mi_tiempo='Hora: {}, Minuto: {}'.format(6,15)
print(mi_tiempo)

Hora: 6, Minuto: 15


In [51]:
print('pi is %f' % 3.14)
print('%s to %s' % ('Welcome', 'QuantConnect'))

pi is 3.140000
Welcome to QuantConnect


In [52]:
print('euler es %f' % 2.71)
print('%s a %s' % ('Bienvenido','QuantConnect'))

euler es 2.710000
Bienvenido a QuantConnect


#TUTORIAL 2

##Logical Operations

In [53]:
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)    # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [54]:
print(0 == 0)
print(2 == 1)
print(0 != 0)
print(9 >= 9)
print(-9 >= 8)

True
False
False
True
False


In [55]:
print (2 > 1) and (3 > 2)
print (2 > 1) and (3 < 2)
print (2 > 1) or  (3 < 2)
print (2 < 1) and (3 < 2)

True
True
True
False


In [56]:
print (-2 > -1) and (-3 > -2)
print (-2 > -1) and (-3 < -2)
print (-2 > -1) or  (-3 < -2)
print (-2 < -1) and (-3 < -2)

False
False
False
True


In [57]:
print (((3 > 2) or (1 < 3)) and ((1!=3) and (4>3)) and not ( (3 < 2) or (1 < 3) and ((1!=3) and (4>3))))
print ((3 > 2) or (1 < 3) and ((1!=3) and (4>3)) and not ( (3 < 2) or (1 < 3) and ((1!=3) and (4>3))))

False
True


In [58]:
print (((-3 > -2) and (-1 < -3)) or ((-1!=-3) or (-4>-3)) or not ( (-3 < -2) and (-1 < -3) or ((-1!=-3) or (-4>-3))))
print ((-3 > -2) and (-1 < -3) or ((-1!=-3) or (-4>-3)) and not ( (-3 < -2) and (-1 < -3) or ((-1!=-3) or (-4>-3))))

True
False


##If Statement

In [59]:
i = 0
if i == 0: print('i == 0 is True')

i == 0 is True


In [60]:
i = 1
if i != 0: print('i != 0 is True')

i != 0 is True


In [61]:
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [62]:
p = 11 < 0
q = -1 < 10
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

p is false


##Loop Structure

###While Loop

In [63]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [64]:
i = 10
while i > 0:
    print(i)
    i -= 1

10
9
8
7
6
5
4
3
2
1


###For Loop

In [65]:
for x in [1,2,3,4,5]: print(x)

1
2
3
4
5


In [66]:
for x in [10,9,8,7,6,5]: print(x-1)

9
8
7
6
5
4


In [67]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [68]:
stocks = ['CA','GOOG','ORACLE','FB','F','V', 'G', 'GE']
selected = ['CA','ORACLE']
new_list = []
for stock in stocks:
    if stock in selected:
        new_list.append(stock)
print(new_list)

['CA', 'ORACLE']


###Break and continue

In [69]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [70]:
stocks = ['AAPL','GOOG','IBM','FB','F','V','BREAK','G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'BREAK': break

AAPL
GOOG
IBM
FB
F
V
BREAK


In [71]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print (stock)

AAPL
GOOG
IBM
F
V
G
GE


In [72]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock != 'V': continue
    print (stock)

V


###List Comprehension

In [73]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [74]:
cubos = []
for i in [-1,-2,-3,-4,-5]:
    cubos.append(i**3)
print(cubos)

[-1, -8, -27, -64, -125]


In [75]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print(squares)

[1, 4, 9, 16, 25]


In [76]:
foo = [1,2,3,4,5]
cubos = [x**3 for x in foo]
print(cubos)

[1, 8, 27, 64, 125]


In [77]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [78]:
lista = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
seleccionado = ['AAPL','IBM']
nueva_lista = [x for x in lista if x in seleccionado]
print(nueva_lista)

['AAPL', 'IBM']


In [79]:
print ([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB'] for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [80]:
print ([(y, x) for x in [4,5,6] for y in [6,4,7] if x==y])
print ([str(x) + ' vs ' + str(y) for x in ['Hola','Adios','Bienvenido'] for y in ['Carlos','Juan','Andrea','Viviana'] if x != y])

[(4, 4), (6, 6)]
['Hola vs Carlos', 'Hola vs Juan', 'Hola vs Andrea', 'Hola vs Viviana', 'Adios vs Carlos', 'Adios vs Juan', 'Adios vs Andrea', 'Adios vs Viviana', 'Bienvenido vs Carlos', 'Bienvenido vs Juan', 'Bienvenido vs Andrea', 'Bienvenido vs Viviana']


#TUTORIAL 3

##Functions

In [81]:
def product(x,y):
    return x*y
print(product(2,3))
print(product(5,10))

6
50


In [82]:
def division(x,y):
    return x/y
print(division(1,4))
print(division(30,10))

0.25
3.0


In [83]:
def say_hi():
    print ("Welcome to QuantConnect")
say_hi()

Welcome to QuantConnect


In [84]:
def decir_hola():
    print ("Hola Mundo")
decir_hola()

Hola Mundo


##Built-in Function

###range()

In [85]:
print(*range(10))
print(*range(1, 11))
print(*range(1, 11, 2))

0 1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9 10
1 3 5 7 9


In [86]:
print(*range(20))
print(*range(5, 12))
print(*range(-5, 14, 3))

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
5 6 7 8 9 10 11
-5 -2 1 4 7 10 13


###len()

In [87]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [88]:
tiquetes = ['UNO', 'DOS', 'TRES', 'CUATRO', 'CINCO']
print("El número de tiquetes es {}".format(len(tiquetes)))
for k in range(len(tiquetes)):
    print(k + 1, tiquetes[k])

El número de tiquetes es 5
1 UNO
2 DOS
3 TRES
4 CUATRO
5 CINCO


###map()

In [89]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [90]:
etiquetas = ['esternocleidomastoideo','electroencefalografista','ORACLE','FACEBOOK']
print(list(map(len,etiquetas)))

[22, 23, 6, 8]


###lambda operator

In [91]:
print(list(map(lambda x: x**2, range(10))))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [92]:
print(list(map(lambda x: x**3, range(5))))

[0, 1, 8, 27, 64]


In [93]:
print(list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1])))

[6, 6, 6, 6, 6]


In [94]:
print(list(map(lambda x, y: x+y, [5,6,7,8,9], [5,4,3,2,1])))

[10, 10, 10, 10, 10]


###sorted()

In [95]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [96]:
sorted([8,5,45,65,84,25,85,56,8])

[5, 8, 8, 25, 45, 56, 65, 84, 85]

In [97]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [98]:
lista_precios = [('PLATANO', 2000), ('YUCA', 1500), ('PAPA', 700), ('TOMATE', 800), ('CEBOLLA', 1000)]
sorted(lista_precios, key = lambda x: x[1])

[('PAPA', 700),
 ('TOMATE', 800),
 ('CEBOLLA', 1000),
 ('YUCA', 1500),
 ('PLATANO', 2000)]

In [99]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [100]:
lista_precios = [('PLATANO', 2000), ('YUCA', 1500), ('PAPA', 700), ('TOMATE', 800), ('CEBOLLA', 1000)]
sorted(lista_precios, key = lambda x: x[1], reverse=True)

[('PLATANO', 2000),
 ('YUCA', 1500),
 ('CEBOLLA', 1000),
 ('TOMATE', 800),
 ('PAPA', 700)]

In [101]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [102]:
price_list = [('PLATANO', 2000), ('YUCA', 1500), ('PAPA', 700), ('TOMATE', 800), ('CEBOLLA', 1000)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('PAPA', 700), ('TOMATE', 800), ('CEBOLLA', 1000), ('YUCA', 1500), ('PLATANO', 2000)]


##Object-Oriented Programming

###Class

In [103]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)

In [104]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

In [105]:
apple.ticker
google.print_return()
google.update(912.8,913.4)
google.print_return()

0.014465338822744034
0.0006573181419806673


In [106]:
hola  = Stock('HOLA', 4, 8, 16)
mundo = Stock('MUNDO', 2, 10, 100)

In [107]:
hola.ticker
mundo.print_return()
mundo.update(912.8,913.4)
mundo.print_return()

4.0
0.0006573181419806673


In [108]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [109]:
hola.ceo = 'Adios'
hola.ceo

'Adios'

In [110]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [111]:
dir(hola)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

###Inheritance

In [112]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [113]:
aa = Child('AA')
print(aa.name)
aa.update(100, 102)
print(aa.open)
print(aa.close)
print(aa.print_return())

AA
100
102
0.020000000000000018
None


In [114]:
mundo = Child('MUNDO')
print(mundo.name)
mundo.update(100, 100)
print(mundo.open)
print(mundo.close)
print(mundo.print_return())

MUNDO
100
100
0.0
None


#TUTORIAL 4

##Numpy

In [115]:
import numpy as np

###Basic NumPy Arrays

In [116]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [117]:
lista_precios = [3.73, 5.83, 3.68, 4.02, 3.50, 2.62]
arreglo_precios = np.array(lista_precios)
print(arreglo_precios, type(arreglo_precios))

[3.73 5.83 3.68 4.02 3.5  2.62] <class 'numpy.ndarray'>


In [118]:
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [119]:
Arreglo = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(Arreglo, type(Arreglo))

[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'>


In [120]:
print(Ar.shape)

(2, 2)


In [121]:
print(Arreglo.shape)

(3, 3)


In [122]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [123]:
print(Arreglo[0])
print(Arreglo[1])
print(Arreglo[2])

[1 0 0]
[0 1 0]
[0 0 1]


In [124]:
print('First column:', Ar[:,0])
print('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


In [125]:
print('First column:', Arreglo[:,0])
print('Second column:', Arreglo[:,1])
print('Third column:', Arreglo[:,2])

First column: [1 0 0]
Second column: [0 1 0]
Third column: [0 0 1]


###Array Functions

In [126]:
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [127]:
np.log(arreglo_precios)

array([1.31640823, 1.763017  , 1.30291275, 1.3912819 , 1.25276297,
       0.96317432])

In [128]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [129]:
print(np.mean(arreglo_precios))
print(np.std(arreglo_precios))
print(np.sum(arreglo_precios))
print(np.max(arreglo_precios))

3.8966666666666665
0.9673790478515762
23.38
5.83


##Pandas

In [130]:
import pandas as pd

###Series

In [131]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [132]:
precio = [1000,2000,500,600,1500,600]
serie = pd.Series(precio)
print(serie)

0    1000
1    2000
2     500
3     600
4    1500
5     600
dtype: int64


In [133]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [134]:
serie = pd.Series(precio, index = ['a', 'b', 'c', 'd', 'e','f'])
print(serie)

a    1000
b    2000
c     500
d     600
e    1500
f     600
dtype: int64


In [135]:
s.index = [6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [136]:
serie.index = [6,5,4,3,2,1]
print(serie)

6    1000
5    2000
4     500
3     600
2    1500
1     600
dtype: int64


In [137]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [138]:
print(serie[1:])
print(serie[:-2])

5    2000
4     500
3     600
2    1500
1     600
dtype: int64
6    1000
5    2000
4     500
3     600
dtype: int64


In [139]:
print(s[4])
s[4] = 0
print(s)


143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [140]:
print(serie[4])
serie[4] = 0
print(serie)


500
6    1000
5    2000
4       0
3     600
2    1500
1     600
dtype: int64


In [141]:
s = pd.Series(price, name = 'Apple Prices')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [142]:
serie = pd.Series(precio, name = 'Precio Manzana')
print(serie)
print(serie.name)

0    1000
1    2000
2     500
3     600
4    1500
5     600
Name: Precio Manzana, dtype: int64
Precio Manzana


In [143]:
print(s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [144]:
print(serie.describe())

count       6.000000
mean     1033.333333
std       602.218122
min       500.000000
25%       600.000000
50%       800.000000
75%      1375.000000
max      2000.000000
Name: Precio Manzana, dtype: float64


###Time Index

In [145]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [146]:
indice_tiempo = pd.date_range('2021-01-01', periods = len(serie), freq = 'D')
print(indice_tiempo)
serie.index = indice_tiempo
print(serie)

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')
2021-01-01    1000
2021-01-02    2000
2021-01-03     500
2021-01-04     600
2021-01-05    1500
2021-01-06     600
Freq: D, Name: Precio Manzana, dtype: int64


In [147]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])


6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [148]:
serie.index = [6,5,4,3,2,1]
print(serie)
print(serie[1])

6    1000
5    2000
4     500
3     600
2    1500
1     600
Name: Precio Manzana, dtype: int64
600


In [149]:
print(s.iloc[1])

145.83


In [150]:
print(serie.iloc[1])

2000


In [151]:
s.index = time_index
print(s['2017-01-01'])

143.73


In [152]:
serie.index = indice_tiempo
print(serie['2021-01-01'])

1000


In [153]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [154]:
print(serie['2021-01-02':'2021-01-05'])

2021-01-02    2000
2021-01-03     500
2021-01-04     600
2021-01-05    1500
Freq: D, Name: Precio Manzana, dtype: int64


In [155]:
print(s[s < np.mean(s)])
print(s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [156]:
print(serie[serie < np.mean(serie)])
print(serie[(serie > np.mean(serie)) & (serie < np.mean(serie) + 1.64*np.std(serie))])

2021-01-01    1000
2021-01-03     500
2021-01-04     600
2021-01-06     600
Name: Precio Manzana, dtype: int64
2021-01-05    1500
Freq: D, Name: Precio Manzana, dtype: int64


#TUTORIAL 5

##Fetching Data

In [157]:
!pip install --upgrade quandl

In [158]:
import quandl
quandl.ApiConfig.api_key = 'DeGodyKnkEDLUzkWSMrn'

In [159]:
aapl_table = quandl.get('WIKI/AAPL')
aapl = aapl_table['Adj. Close']['2017']
print(aapl)

Date
2017-01-03    114.715378
2017-01-04    114.586983
2017-01-05    115.169696
2017-01-06    116.453639
2017-01-09    117.520300
                 ...    
2017-12-22    175.010000
2017-12-26    170.570000
2017-12-27    170.600000
2017-12-28    171.080000
2017-12-29    169.230000
Name: Adj. Close, Length: 249, dtype: float64


In [160]:
print(aapl['2017-3'])

Date
2017-03-01    138.657681
2017-03-02    137.834404
2017-03-03    138.647762
2017-03-06    138.211326
2017-03-07    138.389868
2017-03-08    137.874080
2017-03-09    137.556672
2017-03-10    138.012946
2017-03-13    138.072460
2017-03-14    137.864161
2017-03-15    139.322254
2017-03-16    139.550391
2017-03-17    138.856061
2017-03-20    140.314154
2017-03-21    138.707276
2017-03-22    140.274478
2017-03-23    139.778528
2017-03-24    139.500796
2017-03-27    139.738852
2017-03-28    142.635200
2017-03-29    142.952608
2017-03-30    142.764147
2017-03-31    142.496334
Name: Adj. Close, dtype: float64


In [161]:
aapl['2017-2':'2017-4']

Date
2017-02-01    127.159749
2017-02-02    126.942467
2017-02-03    127.485673
2017-02-06    128.680728
2017-02-07    129.905412
                 ...    
2017-04-24    142.476496
2017-04-25    143.369205
2017-04-26    142.487208
2017-04-27    142.625281
2017-04-28    142.486415
Name: Adj. Close, Length: 61, dtype: float64

In [162]:
print(aapl.head())
print(aapl.tail(10))

Date
2017-01-03    114.715378
2017-01-04    114.586983
2017-01-05    115.169696
2017-01-06    116.453639
2017-01-09    117.520300
Name: Adj. Close, dtype: float64
Date
2017-12-15    173.87
2017-12-18    176.42
2017-12-19    174.54
2017-12-20    174.35
2017-12-21    175.01
2017-12-22    175.01
2017-12-26    170.57
2017-12-27    170.60
2017-12-28    171.08
2017-12-29    169.23
Name: Adj. Close, dtype: float64


##Resampling

In [163]:
by_month = aapl.resample('M').mean()
print(by_month)

Date
2017-01-31    118.093136
2017-02-28    132.456268
2017-03-31    139.478802
2017-04-30    141.728436
2017-05-31    151.386305
2017-06-30    147.233064
2017-07-31    147.706190
2017-08-31    158.856375
2017-09-30    157.606500
2017-10-31    157.811627
2017-11-30    172.214500
2017-12-31    171.893100
Freq: M, Name: Adj. Close, dtype: float64


In [164]:
by_week = aapl.resample('W').mean()
print(by_week.head())


Date
2017-01-08    115.231424
2017-01-15    117.755360
2017-01-22    118.461035
2017-01-29    119.667448
2017-02-05    124.313346
Freq: W-SUN, Name: Adj. Close, dtype: float64


In [165]:
three_day = aapl.resample('3D').mean()
two_week  = aapl.resample('2W').mean()
two_month = aapl.resample('2M').mean()

In [166]:
std = aapl.resample('W').std()    # standard deviation
max = aapl.resample('W').max()    # maximum value
min = aapl.resample('W').min()    # minimum value

In [167]:
last_day = aapl.resample('M').agg(lambda x: x[-1])
print(last_day)

Date
2017-01-31    119.851150
2017-02-28    135.880362
2017-03-31    142.496334
2017-04-30    142.486415
2017-05-31    152.142689
2017-06-30    143.438008
2017-07-31    148.248489
2017-08-31    164.000000
2017-09-30    154.120000
2017-10-31    169.040000
2017-11-30    171.850000
2017-12-31    169.230000
Freq: M, Name: Adj. Close, dtype: float64


In [168]:
monthly_return = aapl.resample('M').agg(lambda x: x[-1]/x[1] - 1)
print(monthly_return)

Date
2017-01-31    0.045940
2017-02-28    0.070409
2017-03-31    0.033823
2017-04-30   -0.007736
2017-05-31    0.039829
2017-06-30   -0.073528
2017-07-31    0.033035
2017-08-31    0.047890
2017-09-30   -0.049112
2017-10-31    0.094252
2017-11-30    0.022247
2017-12-31   -0.003357
Freq: M, Name: Adj. Close, dtype: float64


In [169]:
print(monthly_return.mean())
print(monthly_return.std())
print(monthly_return.max())

0.02114094011940022
0.04775652864223314
0.09425168306576914


In [170]:
print(last_day.diff())
print(last_day.pct_change())

Date
2017-01-31          NaN
2017-02-28    16.029211
2017-03-31     6.615972
2017-04-30    -0.009919
2017-05-31     9.656274
2017-06-30    -8.704681
2017-07-31     4.810482
2017-08-31    15.751511
2017-09-30    -9.880000
2017-10-31    14.920000
2017-11-30     2.810000
2017-12-31    -2.620000
Freq: M, Name: Adj. Close, dtype: float64
Date
2017-01-31         NaN
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64


In [171]:
daily_return = last_day.pct_change()
print(daily_return.fillna(0))

Date
2017-01-31    0.000000
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64


In [172]:
daily_return = last_day.pct_change()
print(daily_return.fillna(method = 'bfill'))

Date
2017-01-31    0.133743
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64


In [173]:
daily_return = last_day.pct_change().dropna()
print(daily_return)

Date
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64


##DataFrame

###Create DataFrames

In [174]:
dict = {'AAPL': [143.5,  144.09, 142.73, 144.18, 143.77],
        'GOOG': [898.7,  911.71, 906.69, 918.59, 926.99],
        'IBM':  [155.58, 153.67, 152.36, 152.94, 153.49]}
dates = pd.date_range('2017-07-03', periods = 5, freq = 'D')
df = pd.DataFrame(dict, index = dates)
print(df)

              AAPL    GOOG     IBM
2017-07-03  143.50  898.70  155.58
2017-07-04  144.09  911.71  153.67
2017-07-05  142.73  906.69  152.36
2017-07-06  144.18  918.59  152.94
2017-07-07  143.77  926.99  153.49


###Manipulating DataFrames

In [175]:
df = aapl_table
print(df.Close.tail(5))
print(df['Adj. Volume'].tail(5))

Date
2018-03-21    171.270
2018-03-22    168.845
2018-03-23    164.940
2018-03-26    172.770
2018-03-27    168.340
Name: Close, dtype: float64
Date
2018-03-21    35247358.0
2018-03-22    41051076.0
2018-03-23    40248954.0
2018-03-26    36272617.0
2018-03-27    38962839.0
Name: Adj. Volume, dtype: float64


In [176]:
aapl_2016 = df['2016']
aapl_month = aapl_2016.resample('M').agg(lambda x: x[-1])
print(aapl_month)

              Open      High     Low  ...    Adj. Low  Adj. Close  Adj. Volume
Date                                  ...                                     
2016-01-31   94.79   97.3400   94.35  ...   91.156128   94.044912   64416504.0
2016-02-29   96.86   98.2300   96.65  ...   93.880927   93.919781   35216277.0
2016-03-31  109.72  109.9000  108.88  ...  105.760531  105.867380   25888449.0
2016-04-30   93.99   94.7200   92.51  ...   89.859540   91.054300   68531478.0
2016-05-31   99.60  100.4000   98.82  ...   96.575559   97.591939   42307212.0
2016-06-30   94.44   95.7700   94.30  ...   92.158220   93.428693   35836356.0
2016-07-31  104.19  104.5500  103.68  ...  101.325177  101.843140   27733688.0
2016-08-31  105.66  106.5699  105.64  ...  103.796505  104.248477   29662406.0
2016-09-30  112.46  113.3700  111.80  ...  109.849008  111.077195   36379106.0
2016-10-31  113.65  114.2300  113.20  ...  111.224577  111.558644   26419398.0
2016-11-30  111.56  112.2000  110.27  ...  108.90800

In [177]:
aapl_bar = aapl_month[['Open', 'High', 'Low', 'Close']]
print(aapl_bar)

              Open      High     Low   Close
Date                                        
2016-01-31   94.79   97.3400   94.35   97.34
2016-02-29   96.86   98.2300   96.65   96.69
2016-03-31  109.72  109.9000  108.88  108.99
2016-04-30   93.99   94.7200   92.51   93.74
2016-05-31   99.60  100.4000   98.82   99.86
2016-06-30   94.44   95.7700   94.30   95.60
2016-07-31  104.19  104.5500  103.68  104.21
2016-08-31  105.66  106.5699  105.64  106.10
2016-09-30  112.46  113.3700  111.80  113.05
2016-10-31  113.65  114.2300  113.20  113.54
2016-11-30  111.56  112.2000  110.27  110.52
2016-12-31  116.65  117.2000  115.43  115.82


In [178]:
print(aapl_month.loc['2016-03':'2016-06', ['Open', 'High', 'Low', 'Close']])

              Open    High     Low   Close
Date                                      
2016-03-31  109.72  109.90  108.88  108.99
2016-04-30   93.99   94.72   92.51   93.74
2016-05-31   99.60  100.40   98.82   99.86
2016-06-30   94.44   95.77   94.30   95.60


In [179]:
above = aapl_bar[aapl_bar.Close > np.mean(aapl_bar.Close)]
print(above)

              Open      High     Low   Close
Date                                        
2016-03-31  109.72  109.9000  108.88  108.99
2016-08-31  105.66  106.5699  105.64  106.10
2016-09-30  112.46  113.3700  111.80  113.05
2016-10-31  113.65  114.2300  113.20  113.54
2016-11-30  111.56  112.2000  110.27  110.52
2016-12-31  116.65  117.2000  115.43  115.82


###Data Validation

In [180]:
aapl_bar['rate_return'] = aapl_bar.Close.pct_change()
print(aapl_bar)

              Open      High     Low   Close  rate_return
Date                                                     
2016-01-31   94.79   97.3400   94.35   97.34          NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [181]:
missing = aapl_bar.isnull()
print(missing)
print('---------------------------------------------')
print(missing.describe())

             Open   High    Low  Close  rate_return
Date                                               
2016-01-31  False  False  False  False         True
2016-02-29  False  False  False  False        False
2016-03-31  False  False  False  False        False
2016-04-30  False  False  False  False        False
2016-05-31  False  False  False  False        False
2016-06-30  False  False  False  False        False
2016-07-31  False  False  False  False        False
2016-08-31  False  False  False  False        False
2016-09-30  False  False  False  False        False
2016-10-31  False  False  False  False        False
2016-11-30  False  False  False  False        False
2016-12-31  False  False  False  False        False
---------------------------------------------
         Open   High    Low  Close rate_return
count      12     12     12     12          12
unique      1      1      1      1           2
top     False  False  False  False       False
freq       12     12     12     12    

In [182]:
print(missing[missing.rate_return == True])

             Open   High    Low  Close  rate_return
Date                                               
2016-01-31  False  False  False  False         True


In [183]:
drop = aapl_bar.dropna()
print(drop)
print('\n--------------------------------------------------\n')
fill = aapl_bar.fillna(0)
print(fill)

              Open      High     Low   Close  rate_return
Date                                                     
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955

--------------------------------------------------

              Open      High     Low   Close  rate_return
Date                                                     
2016-01-31   94.79   97.3400   94.35   97.34     0.000000
2016-02-29   96.86 

###DataFrame Concat

In [184]:
s1 = pd.Series([143.5, 144.09, 142.73, 144.18, 143.77], name = 'AAPL')
s2 = pd.Series([898.7, 911.71, 906.69, 918.59, 926.99], name = 'GOOG')
data_frame = pd.concat([s1, s2], axis = 1)
print(data_frame)

     AAPL    GOOG
0  143.50  898.70
1  144.09  911.71
2  142.73  906.69
3  144.18  918.59
4  143.77  926.99


In [185]:
log_price = np.log(aapl_bar.Close)
log_price.name = 'log_price'
print(log_price)
print('\n--------------------------------------------\n')
concat = pd.concat([aapl_bar, log_price], axis = 1)
print(concat)

Date
2016-01-31    4.578210
2016-02-29    4.571510
2016-03-31    4.691256
2016-04-30    4.540525
2016-05-31    4.603769
2016-06-30    4.560173
2016-07-31    4.646408
2016-08-31    4.664382
2016-09-30    4.727830
2016-10-31    4.732155
2016-11-30    4.705197
2016-12-31    4.752037
Freq: M, Name: log_price, dtype: float64

--------------------------------------------

              Open      High     Low   Close  rate_return  log_price
Date                                                                
2016-01-31   94.79   97.3400   94.35   97.34          NaN   4.578210
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678   4.571510
2016-03-31  109.72  109.9000  108.88  108.99     0.127211   4.691256
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921   4.540525
2016-05-31   99.60  100.4000   98.82   99.86     0.065287   4.603769
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660   4.560173
2016-07-31  104.19  104.5500  103.68  104.21     0.090063   4.646408
2016-08-31

In [186]:
df_volume = aapl_table.loc['2016-10':'2017-04', ['Volume', 'Split Ratio']].resample('M').agg(lambda x: x[-1])
print(df_volume)
print('\n-------------------------------------------\n')
df_2017 = aapl_table.loc['2016-10':'2017-04', ['Open', 'High', 'Low', 'Close']].resample('M').agg(lambda x: x[-1])
print(df_2017)

                Volume  Split Ratio
Date                               
2016-10-31  26419398.0          1.0
2016-11-30  36162258.0          1.0
2016-12-31  30586265.0          1.0
2017-01-31  49200993.0          1.0
2017-02-28  23482860.0          1.0
2017-03-31  19661651.0          1.0
2017-04-30  20247187.0          1.0

-------------------------------------------

              Open     High     Low   Close
Date                                       
2016-10-31  113.65  114.230  113.20  113.54
2016-11-30  111.56  112.200  110.27  110.52
2016-12-31  116.65  117.200  115.43  115.82
2017-01-31  121.15  121.390  120.62  121.35
2017-02-28  137.08  137.435  136.70  136.99
2017-03-31  143.72  144.270  143.01  143.66
2017-04-30  144.09  144.300  143.27  143.65


In [187]:
concat = pd.concat([aapl_bar, df_volume], axis = 1)
print(concat)

              Open      High     Low  ...  rate_return      Volume  Split Ratio
Date                                  ...                                      
2016-01-31   94.79   97.3400   94.35  ...          NaN         NaN          NaN
2016-02-29   96.86   98.2300   96.65  ...    -0.006678         NaN          NaN
2016-03-31  109.72  109.9000  108.88  ...     0.127211         NaN          NaN
2016-04-30   93.99   94.7200   92.51  ...    -0.139921         NaN          NaN
2016-05-31   99.60  100.4000   98.82  ...     0.065287         NaN          NaN
2016-06-30   94.44   95.7700   94.30  ...    -0.042660         NaN          NaN
2016-07-31  104.19  104.5500  103.68  ...     0.090063         NaN          NaN
2016-08-31  105.66  106.5699  105.64  ...     0.018136         NaN          NaN
2016-09-30  112.46  113.3700  111.80  ...     0.065504         NaN          NaN
2016-10-31  113.65  114.2300  113.20  ...     0.004334  26419398.0          1.0
2016-11-30  111.56  112.2000  110.27  ..

In [188]:
concat = pd.concat([aapl_bar, df_volume], axis = 1, join = 'inner')
print(concat)

              Open    High     Low  ...  rate_return      Volume  Split Ratio
Date                                ...                                      
2016-10-31  113.65  114.23  113.20  ...     0.004334  26419398.0          1.0
2016-11-30  111.56  112.20  110.27  ...    -0.026599  36162258.0          1.0
2016-12-31  116.65  117.20  115.43  ...     0.047955  30586265.0          1.0

[3 rows x 7 columns]


In [189]:
append = aapl_bar.append(df_2017)
print(append)

              Open      High     Low   Close  rate_return
Date                                                     
2016-01-31   94.79   97.3400   94.35   97.34          NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955
2016-10-31  113.65  114.2300  113.20  113.54          NaN
2016-11-30  111.56  112.2000  110.27  110.52          NaN
2016-12-31  116.65  117.2000  115.43  115.82          NaN
2017-01-31  12

In [190]:
concat = pd.concat([aapl_bar, df_2017], axis = 0)
print(concat)

              Open      High     Low   Close  rate_return
Date                                                     
2016-01-31   94.79   97.3400   94.35   97.34          NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955
2016-10-31  113.65  114.2300  113.20  113.54          NaN
2016-11-30  111.56  112.2000  110.27  110.52          NaN
2016-12-31  116.65  117.2000  115.43  115.82          NaN
2017-01-31  12

In [191]:
df_2017.columns = ['Change', 'High', 'Low', 'Close']
concat = pd.concat([aapl_bar, df_2017], axis = 0)
print(concat)

              Open      High     Low   Close  rate_return  Change
Date                                                             
2016-01-31   94.79   97.3400   94.35   97.34          NaN     NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678     NaN
2016-03-31  109.72  109.9000  108.88  108.99     0.127211     NaN
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921     NaN
2016-05-31   99.60  100.4000   98.82   99.86     0.065287     NaN
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660     NaN
2016-07-31  104.19  104.5500  103.68  104.21     0.090063     NaN
2016-08-31  105.66  106.5699  105.64  106.10     0.018136     NaN
2016-09-30  112.46  113.3700  111.80  113.05     0.065504     NaN
2016-10-31  113.65  114.2300  113.20  113.54     0.004334     NaN
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599     NaN
2016-12-31  116.65  117.2000  115.43  115.82     0.047955     NaN
2016-10-31     NaN  114.2300  113.20  113.54          NaN  113.65
2016-11-30